UPDATE products SET inStock = 18 where name='33 Export';
UPDATE products SET inStock = 1 where name='4 Cousins Sweet White';
UPDATE products SET inStock = 3 where name='Baron Blanc de Blancs';
UPDATE products SET inStock = 15 where name='BAVARIA';
UPDATE products SET inStock = 130 where name='BEAUFORT GRAND';
UPDATE products SET inStock = 75 where name='BEAUFORT PETIT';
UPDATE products SET inStock = 127 where name='CASTEL';
UPDATE products SET inStock = 2 where name='Champagne Billecart-salmon réserve';
UPDATE products SET inStock = 17 where name='COCA EN BOUTEILLE';
UPDATE products SET inStock = 17 where name='COCA ZERO';
UPDATE products SET inStock = 19 where name='CORONA';
UPDATE products SET inStock = 4 where name='Don Oscart';
UPDATE products SET inStock = 36 where name='Duvel';
UPDATE products SET inStock = 1 where name='Duvel Grand';
UPDATE products SET inStock = 16 where name='EAU';
UPDATE products SET inStock = 1 where name='Eau Gazeuse';
UPDATE products SET inStock = 15 where name='Energie Malt';
UPDATE products SET inStock = 19 where name='Guinness';
UPDATE products SET inStock = 37 where name='HEINEKEN';
UPDATE products SET inStock = 17 where name='Heineken importée';
UPDATE products SET inStock = 15 where name='Heineken Zéro';
UPDATE products SET inStock = 43 where name='LEFFE BRUNE';
UPDATE products SET inStock = 16 where name='LEGEND';
UPDATE products SET inStock = 8 where name='Maltina';
UPDATE products SET inStock = 1 where name='Martini sans Alcool';
UPDATE products SET inStock = 13 where name='MUTZIG';
UPDATE products SET inStock = 17 where name='NKOYI';
UPDATE products SET inStock = 5 where name='Papillon Brut';
UPDATE products SET inStock = 3 where name='Pierre Grandet';
UPDATE products SET inStock = 6 where name='Primus La Petite';
UPDATE products SET inStock = 20 where name='REDBULL';
UPDATE products SET inStock = 2 where name='Ruinart Blanc de Blancs';
UPDATE products SET inStock = 1 where name='Ruinart Brut';
UPDATE products SET inStock = 14 where name='SAVANA';
UPDATE products SET inStock = 13 where name='SODA';
UPDATE products SET inStock = 24 where name='SPRITE';
UPDATE products SET inStock = 9 where name='Stella Artois Bouteilles';
UPDATE products SET inStock = 62 where name='TEMBO BOUTEILLE';
UPDATE products SET inStock = 45 where name='TONIC';
UPDATE products SET inStock = 5 where name='TURBO KING';
UPDATE products SET inStock = 1 where name="Vin Baron d'arignac Sec";
UPDATE products SET inStock = 1 where name="Vin Rouge Celier D'Or sec";
UPDATE products SET inStock = 29 where name='VITALO';
UPDATE products SET inStock = 13 where name='XXL';
