UPDATE products SET barStock = 3, type="Spiritueux" where name="Bouteille Glenfiddich 15ans";
UPDATE products SET barStock = 1, type="Spiritueux" where name="Ruinart Brut";
UPDATE products SET barStock = 1, type="Spiritueux" where name="Baron Blanc de Blancs";
UPDATE products SET barStock = 2, type="Spiritueux" where name="Bouteille Disaronno";
UPDATE products SET barStock = 12, type="Spiritueux" where name="Mesure Grundheim";
UPDATE products SET barStock = 11, type="Spiritueux" where name="Mesures Grand Marnier";
UPDATE products SET barStock = 1, type="Spiritueux" where name="Bouteille Martel";
UPDATE products SET barStock = 1, type="Spiritueux" where name="Bouteille de Jägermeifter";
UPDATE products SET barStock = 2, type="Spiritueux" where name="Glenfiddich 18 yrs";
UPDATE products SET barStock = 3, type="Spiritueux" where name="Baron D'arignac rouge moelleux";
UPDATE products SET barStock = 2, type="Spiritueux" where name="Baron D'arignac Rouge Sec";
UPDATE products SET barStock = 1, type="Spiritueux" where name="Jack Daniels Gentleman 70 cl";
UPDATE products SET barStock = 3, type="Spiritueux" where name="Champagne Billecart-salmon réserve";
UPDATE products SET barStock = 2, type="Spiritueux" where name="Sir Edward Smoky";
UPDATE products SET barStock = 2, type="Spiritueux" where name="Mateus";
UPDATE products SET barStock = 1, type="Spiritueux" where name="Vin Blanc Domaine de Baume";
UPDATE products SET barStock = 9, type="Spiritueux" where name="Bouteille de Red Label 37.5cl";
UPDATE products SET barStock = 8, type="Spiritueux" where name="Bouteille de Black Label 37.5cl";
UPDATE products SET barStock = 1, type="Spiritueux" where name="Ruinart Petit Brut";
UPDATE products SET barStock = 8, type="Spiritueux" where name="4 Cousins Sweet White";
UPDATE products SET barStock = 7, type="Spiritueux" where name="Papillon Brut";
UPDATE products SET barStock = 2, type="Spiritueux" where name="Bouteille Martell Blue Swift";
UPDATE products SET barStock = 2, type="Spiritueux" where name="Martini sans Alcool";
UPDATE products SET barStock = 6, type="Spiritueux" where name="Don Oscart";
