UPDATE products SET barStock = 6 where name="4 Cousins Chardonnay Blanc";
UPDATE products SET barStock = 2 where name="4 Cousins Rouge Merlot";
UPDATE products SET barStock = 4 where name="4 Cousins Sauvignon Blanc";
UPDATE products SET barStock = 0 where name="4 Cousins Sauvignon Rouge";
UPDATE products SET barStock = 3 where name="BARON ICE";
UPDATE products SET barStock = 0 where name="Bouteille Capitain Morgan";
UPDATE products SET barStock = 2 where name="Bouteille de AMARULA";
UPDATE products SET barStock = 2 where name="Bouteille de BAILEYS";
UPDATE products SET barStock = 10 where name="Bouteille de BLACK LABEL";
UPDATE products SET barStock = 2 where name="Bouteille de CHIVAS 12yrs";
UPDATE products SET barStock = 2 where name="Bouteille de CHIVAS 15ans";
UPDATE products SET barStock = 2 where name="Bouteille de CHIVAS 18ans";
UPDATE products SET barStock = 0 where name="Bouteille de Courvoisier";
UPDATE products SET barStock = 4 where name="Bouteille de DOUBLE BLACK 75cl";
UPDATE products SET barStock = 3 where name="Bouteille de GIN BOMBAY 75cl";
UPDATE products SET barStock = 4 where name="Bouteille de GIN GORDON";
UPDATE products SET barStock = 2 where name="Bouteille de HENNESSY";
UPDATE products SET barStock = 1 where name="Bouteille de J&B";
UPDATE products SET barStock = 1 where name="Bouteille de JACK DANIEL'S";
UPDATE products SET barStock = 0 where name="Bouteille de JACK DANIEL'S HONEY";
UPDATE products SET barStock = 1 where name="Bouteille de JAMSON";
UPDATE products SET barStock = 2 where name="Bouteille de MALIBU";
UPDATE products SET barStock = 1 where name="Bouteille de MARTINI BLANC";
UPDATE products SET barStock = 1 where name="Bouteille de MARTINI ROUGE";
UPDATE products SET barStock = 2 where name="Bouteille de RED LABEL";
UPDATE products SET barStock = 0 where name="Bouteille de VIN BLANC Demi Sec";
UPDATE products SET barStock = 0 where name="Bouteille de VIN ROUGE";
UPDATE products SET barStock = 2 where name="Bouteille Glenfiddich 12ans";
UPDATE products SET barStock = 0 where name="Bouteille Jack Daniel's 1L";
UPDATE products SET barStock = 3 where name="Bouteille SIR EDWARD’S";
UPDATE products SET barStock = 0 where name="Bouteille Vin Montard Ice";
UPDATE products SET barStock = 0 where name="Bt Chivas 18ans 1 Litre";
UPDATE products SET barStock = 0 where name="Chivas 12Y Mesures";
UPDATE products SET barStock = 0 where name="Chivas 15 ans mesures";
UPDATE products SET barStock = 0 where name="Cognac Bisquit Mesure";
UPDATE products SET barStock = 0 where name="Hennessy 1Litre";
UPDATE products SET barStock = 0 where name="Jack Daniel's Gentleman 1L";
UPDATE products SET barStock = 4 where name="Johnny Walker Gold 75Cl";
UPDATE products SET barStock = 12 where name="L.-E Cabernet Sauvignon";
UPDATE products SET barStock = 11 where name="L.-E Merlot";
UPDATE products SET barStock = 9 where name="L.-E Sauvignon Blanc";
UPDATE products SET barStock = 0 where name="LAGAVULIN Mesures";
UPDATE products SET barStock = 0 where name="Mesure d'Amarula";
UPDATE products SET barStock = 0 where name="Mesure de Absolut VODKA";
UPDATE products SET barStock = 0 where name="Mesure de Absolut VODKA VANILLE";
UPDATE products SET barStock = 1 where name="Mesure de Bacardi Blanc";
UPDATE products SET barStock = 0 where name="Mesure de Bacardi Brun";
UPDATE products SET barStock = 0 where name="Mesure de Baileys";
UPDATE products SET barStock = 0 where name="Mesure de Black Label";
UPDATE products SET barStock = 12 where name="Mesure de Blue Label";
UPDATE products SET barStock = 0 where name="Mesure de Campari";
UPDATE products SET barStock = 0 where name="Mesure de CAPITAINE MORGAN";
UPDATE products SET barStock = 0 where name="Mesure de COINTREAU";
UPDATE products SET barStock = 0 where name="Mesure de DISARONNO";
UPDATE products SET barStock = 0 where name="Mesure de DOUBLE BLACK";
UPDATE products SET barStock = 0 where name="Mesure de GET 27";
UPDATE products SET barStock = 0 where name="Mesure de GIN BOMBAY";
UPDATE products SET barStock = 0 where name="Mesure de GIN GORDON";
UPDATE products SET barStock = 0 where name="Mesure de HENNESSY";
UPDATE products SET barStock = 0 where name="Mesure de J&B";
UPDATE products SET barStock = 0 where name="Mesure de JACK DANIEL'S HONEY";
UPDATE products SET barStock = 0 where name="Mesure de JACK DANIELS";
UPDATE products SET barStock = 0 where name="Mesure de JÄGERMEIFTER";
UPDATE products SET barStock = 0 where name="Mesure de JAMSON";
UPDATE products SET barStock = 0 where name="Mesure de LIMONCELLO";
UPDATE products SET barStock = 0 where name="Mesure de MALIBU";
UPDATE products SET barStock = 0 where name="Mesure de MARTINI BLANC";
UPDATE products SET barStock = 0 where name="Mesure de MARTINI ROUGE";
UPDATE products SET barStock = 0 where name="Mesure de RED LABEL";
UPDATE products SET barStock = 0 where name="Mesure de RICARD";
UPDATE products SET barStock = 0 where name="Mesure de Sheridan's";
UPDATE products SET barStock = 12 where name="Mesure de TEQUILA Camilo";
UPDATE products SET barStock = 0 where name="Mesure Glenfiddish 12 ans";
UPDATE products SET barStock = 0 where name="Mesure Jack Daniel Single Barrel";
UPDATE products SET barStock = 0 where name="Mesures Johnny Walker Gold";
UPDATE products SET barStock = 0 where name="MOET BRUT 75cl";
UPDATE products SET barStock = 7 where name="Moet Brut Moyen";
UPDATE products SET barStock = 0 where name="MOET ICE";
UPDATE products SET barStock = 0 where name="Ms Kraken";
UPDATE products SET barStock = 5 where name="Vin Baron d’Arignac Demi Sec";
UPDATE products SET barStock = 0 where name="Vin Cinsault Rose";
UPDATE products SET barStock = 0 where name="Vin Kiss me now";
UPDATE products SET barStock = 0 where name="Vin Merlot Cabernet Bordeaux";
UPDATE products SET barStock = 0 where name="Vin Rosé Bordeaux";
UPDATE products SET barStock = 0 where name="Vin Rouge Cabernet Sauvignon";
UPDATE products SET barStock = 0 where name="Vin Rouge Fleur Du Cap";
UPDATE products SET barStock = 0 where name="Vin Rouge Haut de Médoc";
UPDATE products SET barStock = 0 where name="Vin Rouge Le Bonheur Sauvignon";
UPDATE products SET barStock = 0 where name="Vin Rouge Mouton Cadet";
UPDATE products SET barStock = 0 where name="Vin Rouge Zonneblom Cabernet";
UPDATE products SET barStock = 3 where name="Papillon Demi Sec";
UPDATE products SET barStock = 5 where name="DON OSCART ROSEE";
UPDATE products SET barStock = 4 where name="DON OSCART BLANC DE BLANC";
